IconPath = {}
IconPath.tongyong = "NewUi/xinqietu/tongyong/" --通用
IconPath.pinzhi = "NewUi/xinqietu/tongyong/pinzhi/" --品质路径
IconPath.pinzhiYaun = "NewUi/xinqietu/tongyong/pinzhi/i_head_color_" --品质圆
IconPath.pinzhiKuang = "NewUi/xinqietu/tongyong/pinzhi/i_kuang" --品质圆
IconPath.zhiye = "NewUi/xinqietu/zhiye/car_" --职业路径
IconPath.duiwupeizhi = "NewUi/xinqietu/duiwupeizhi/" --队伍配置
IconPath.fuben = "NewUi/xinqietu/fuben/" --副本
IconPath.zhaomu = "NewUi/xinqietu/zhaomu/" --招募
IconPath.tuanchangjineng = "NewUi/xinqietu/tuanchangjineng/" --团长技能
IconPath.qiming = "NewUi/xinqietu/qiming/" --起名
IconPath.caidan = "NewUi/xinqietu/caidan/" --菜单
IconPath.renwu = "NewUi/xinqietu/renwu/"--任务
IconPath.wenhaogantanhao = "NewUi/xinqietu/wenhaogantanhao/"--任务
IconPath.shijiehuise = "NewUi/xinqietu/worldmap/gray/"--世界地图灰色
IconPath.shijiegaoliang = "NewUi/xinqietu/worldmap/light/"--世界地图高亮
IconPath.shijiezhengchang = "NewUi/xinqietu/worldmap/normal/"--世界地图正常
IconPath.shuxingtishi = "NewUi/xinqietu/shuxingtishi/"--属性提示
IconPath.shenghuojineng = "NewUi/xinqietu/shenghuojineng/"--生活技能
IconPath.youjian = "NewUi/xinqietu/youjian/"--邮件
IconPath.zhandou = "NewUi/xinqietu/zhandou/" --战斗
IconPath.caiji = "NewUi/xinqietu/caiji/" --采集
IconPath.yingxiongshenxing = "NewUi/xinqietu/yingxiongshenxing/" --升星
IconPath.duanzao = "NewUi/xinqietu/duanzao/" --锻造
IconPath.tansuo = "NewUi/xinqietu/tanhsuo/" --探索
IconPath.duanzao = "NewUi/xinqietu/duanzao/" --锻造
IconPath.tansuo = "NewUi/xinqietu/tanhsuo/" --探索
IconPath.xuanqu = "NewUi/xinqietu/xuanqu/"	-- 选区
IconPath.baoshibeijing = "NewUi/xinqietu/baoshi/"	-- 宝石
IconPath.liaotian = "NewUi/xinqietu/liaotian/"	-- 聊天
IconPath.jiesuanshuju = "NewUi/xinqietu/jiesuanshuju/"	-- 结算
IconPath.jingjichang = "NewUi/xinqietu/jingjichang/"	-- 竞技场

IconPath.yingxiong = "res/hero_icon/" --英雄头像
IconPath.jineng = "res/hero_skill/" --技能头像
IconPath.caikuang = "res/acquisition/" --采矿
IconPath.tuanji = "res/team_skill/"--团长技能
IconPath.daoju = "res/tool/"--道具
IconPath.fubenbeijing = "res/force_bg/"--副本
IconPath.baoshi = "res/gem/"--宝石
IconPath.zhuangbei = "res/equip/"--装备
IconPath.tansuoditu = "res/explore_map/"--探索
IconPath.npc = "res/npc/"--npc
IconPath.ditu = "tileMap/ditu/"--地图
IconPath.town = "NewUi/xinqietu/worldmap/town/"--城镇
IconPath.point = "NewUi/xinqietu/worldmap/point/"--当前位置
IconPath.huangguan = "NewUi/xinqietu/haoyou/"--皇冠
IconPath.designation = "NewUi/xinqietu/paihangbang/"--称号