-------------------------------------------------------------------------
--
-- 文 件 名 ：LabelChStr.lua
-- 创 建 者 ：liwentao
-- 创建时间 ：2014-6
-- 功能描述 ：Label中中文字符串管理器，统一管理中文字符串，助于国际化版本
-- 添加规则 ：1、格式 --> LabelChineseStr.文件名_num = 中文字符串
--            2、说明：num依次增加
-------------------------------------------------------------------------

LabelChineseStr = {}

LabelChineseStr.NetEventHandler_1 = "正在重新登录，请稍后"
LabelChineseStr.NetEventHandler_2 = "网络重连中，请稍后"
LabelChineseStr.NetEventHandler_3 = "网络重连失败，是否重试?"
LabelChineseStr.NetEventHandler_4 = "网络重连中，请稍后"
LabelChineseStr.NetEventHandler_5 = "网络断开，是否重连?"
LabelChineseStr.NetEventHandler_6 = "正在重新登录，请稍后"
LabelChineseStr.NetEventHandler_7 = "账号在其它地方登录? 是否重新登录"
LabelChineseStr.NetEventHandler_8 = "网络连接错误：\n"
LabelChineseStr.NetEventHandler_9 = "请检查网络设置"
LabelChineseStr.NetEventHandler_10 = "网络重连中，请稍后"

LabelChineseStr.common_zuanshi = "钻石"
LabelChineseStr.common_jinbi = "金币"
LabelChineseStr.common_null = "暂未开放"
LabelChineseStr.common_miao = "秒"

LabelChineseStr.ExploreRefreshTipUIPanel_1 = "是否消耗["
LabelChineseStr.ExploreRefreshTipUIPanel_2 = "]刷新探索区域"
LabelChineseStr.ExploreRefreshTipUIPanel_3 = "开启自动搜索后,每次消耗["
LabelChineseStr.ExploreRefreshTipUIPanel_4 = "],直到探索到新的英雄或手动方可停止,确认开始自动搜索"
LabelChineseStr.ExploreUIPanel_1 = "级开放探索"
LabelChineseStr.ExploreUIPanel_2 = "总花费钻石:"
LabelChineseStr.ExploreUIPanel_3 = "探索次数已用完"
LabelChineseStr.EmailSenderUIPanel_1 = "点击输入"
LabelChineseStr.EmailSenderUIPanel_2 = "点击输入内容"
LabelChineseStr.EmailSenderUIPanel_3 = "(还可以输入"
LabelChineseStr.EmailSenderUIPanel_4 = "字)"
LabelChineseStr.EmailSenderUIPanel_5 = "发送成功!"
LabelChineseStr.EmailReceiverUIPanel_0 = "已拒绝申请"
LabelChineseStr.EmailReceiverUIPanel_1 = "已添加好友"
LabelChineseStr.EmailUIPanel_1 = "剩余"
LabelChineseStr.EmailUIPanel_2 = "天"
LabelChineseStr.EmailUIPanel_3 = "未勾选任何邮件"
LabelChineseStr.EmailUIPanel_4 = "删除成功"
LabelChineseStr.EmailUIPanel_5 = "邮件中含有未领取的附件，是否删除？"
LabelChineseStr.EmailUIPanel_6 = "一键全选"
LabelChineseStr.EmailUIPanel_7 = "取消全选"
LabelChineseStr.FriendAddUIPanel_1 = "请输入昵称!"
LabelChineseStr.FriendUIPanel_1 = "级开放好友"
LabelChineseStr.FriendUIPanel_2 = "好友数量:"
LabelChineseStr.FriendUIPanel_3 = "黑名单数量:"
LabelChineseStr.FriendUIPanel_4 = "请求发送成功,请耐心等待"
LabelChineseStr.FriendUIPanel_5 = "已加入黑名单"
LabelChineseStr.FriendUIPanel_6 = "已从黑名单移除"
LabelChineseStr.FriendUIPanel_7 = "未选中要移除的对象"
LabelChineseStr.ChatUIPanel_1 = "世 界"
LabelChineseStr.ChatUIPanel_2 = "阵 营"
LabelChineseStr.ChatUIPanel_3 = "公 会"
LabelChineseStr.ChatUIPanel_4 = "私 聊"
LabelChineseStr.ChatUIPanel_0 = "附 近"
LabelChineseStr.ChatUIPanel_5 = "请先输入内容"
LabelChineseStr.ChatUIPanel_6 = "私聊对象为空"
LabelChineseStr.ChatUIPanel_7 = "你还不是公会成员"
LabelChineseStr.ChatUIPanel_8 = "无"
LabelChineseStr.ChatUIPanel_9 = "私 聊"
LabelChineseStr.ChatUIPanel_11 = "阵 营"
LabelChineseStr.PawnShopUIPanel_1 = "您不拥有该物品!"
LabelChineseStr.PawnShopUIPanel_2 = "您的金币不足!"
LabelChineseStr.PawnShopUIPanel_3 = "未选中!"
LabelChineseStr.PawnNumSelectUIPanel_1 = "您想要买入\""
LabelChineseStr.PawnNumSelectUIPanel_2 = "您想要卖出\""
LabelChineseStr.PawnNumSelectUIPanel_3 = "\"的数量"
LabelChineseStr.PawnNumSelectUIPanel_4 = "花费:"
LabelChineseStr.PawnNumSelectUIPanel_5 = "获得:"
LabelChineseStr.PawnNumSelectUIPanel_6 = "您的金币不足!"
LabelChineseStr.PawnNumSelectUIPanel_7 = "已达到物品最大数量!"
LabelChineseStr.PawnNumSelectUIPanel_8 = "已达到可操作的最小数量!"
LabelChineseStr.PawnNumSelectUIPanel_9 = "库存不足!"
LabelChineseStr.HeroInfoUIPanel_1 = "穿戴成功!"
LabelChineseStr.HeroInfoUIPanel_2 = "英雄等级不够!"
LabelChineseStr.HeroInfoUIPanel_3 = "英雄职业不符!"
LabelChineseStr.HeroInfoUIPanel_4 = "穿错位置啦!"
LabelChineseStr.HeroInfoUIPanel_5 = "卸下成功!"
LabelChineseStr.HeroInfoUIPanel_6 = "遣散成功!"
--装备属性用到的字段
LabelChineseStr.ToolDetailUIPanel_1 = "唯一"
LabelChineseStr.ToolDetailUIPanel_2_1 = "单手 剑"
LabelChineseStr.ToolDetailUIPanel_2_2 = "双手 剑"
LabelChineseStr.ToolDetailUIPanel_2_3 = "单手 斧"
LabelChineseStr.ToolDetailUIPanel_2_4 = "双手 斧"
LabelChineseStr.ToolDetailUIPanel_2_5 = "弓"
LabelChineseStr.ToolDetailUIPanel_2_6 = "火枪"
LabelChineseStr.ToolDetailUIPanel_2_7 = "匕首"
LabelChineseStr.ToolDetailUIPanel_2_8 = "双手 法杖"
LabelChineseStr.ToolDetailUIPanel_2_9 = "单手 锤"
LabelChineseStr.ToolDetailUIPanel_2_10 = "双手 锤"
LabelChineseStr.ToolDetailUIPanel_2_11 = "盾"
LabelChineseStr.ToolDetailUIPanel_2_12 = "防具"
LabelChineseStr.ToolDetailUIPanel_3_random = ""
LabelChineseStr.ToolDetailUIPanel_3_damage = "伤害"
LabelChineseStr.ToolDetailUIPanel_3_strength = "力量"
LabelChineseStr.ToolDetailUIPanel_3_agile = "敏捷"
LabelChineseStr.ToolDetailUIPanel_3_intelligence = "智力"
LabelChineseStr.ToolDetailUIPanel_3_stamina = "耐力"
LabelChineseStr.ToolDetailUIPanel_3_hp = "生命值"
LabelChineseStr.ToolDetailUIPanel_3_magic = "法力值"
LabelChineseStr.ToolDetailUIPanel_3_attackPower = "攻击强度"
LabelChineseStr.ToolDetailUIPanel_3_magicPower = "法术强度"
LabelChineseStr.ToolDetailUIPanel_3_phyCrit = "暴击"
LabelChineseStr.ToolDetailUIPanel_3_armor = "护甲"
LabelChineseStr.ToolDetailUIPanel_3_dodge = "闪避"
LabelChineseStr.ToolDetailUIPanel_3_speedUp = "急速"
LabelChineseStr.ToolDetailUIPanel_3_damageIncrease = "伤害增幅"
LabelChineseStr.ToolDetailUIPanel_3_toughIncrease = "伤害减免"
LabelChineseStr.ToolDetailUIPanel_3_treatmentIncrease = "治疗增幅"
LabelChineseStr.ToolDetailUIPanel_3_parry = "格挡"
LabelChineseStr.ToolDetailUIPanel_4 = "职业:"
LabelChineseStr.ToolDetailUIPanel_4_0 = "全职业"
LabelChineseStr.ToolDetailUIPanel_4_1 = "输出战士"
LabelChineseStr.ToolDetailUIPanel_4_2 = "防御战士"
LabelChineseStr.ToolDetailUIPanel_4_3 = "熊德"
LabelChineseStr.ToolDetailUIPanel_4_4 = "树德"
LabelChineseStr.ToolDetailUIPanel_4_5 = "防御骑士"
LabelChineseStr.ToolDetailUIPanel_4_6 = "奶骑士"
LabelChineseStr.ToolDetailUIPanel_4_7 = "法师"
LabelChineseStr.ToolDetailUIPanel_4_8 = "盗贼"
LabelChineseStr.ToolDetailUIPanel_4_9 = "牧师"
LabelChineseStr.ToolDetailUIPanel_4_10 = "术士"
LabelChineseStr.ToolDetailUIPanel_4_11 = "猎人"
LabelChineseStr.ToolDetailUIPanel_4_12 = "元素萨满"
LabelChineseStr.ToolDetailUIPanel_4_13 = "奶萨满"
LabelChineseStr.ToolDetailUIPanel_5 = "需要等级:"
LabelChineseStr.ToolDetailUIPanel_6_cd = "冷却时间:"
LabelChineseStr.PackageUIPanel_1 = "解锁格子"
LabelChineseStr.PackageUIPanel_2 = "需要花费:"
LabelChineseStr.PackageUIPanelDialogTitle_1 = "是否丢弃该道具?"
LabelChineseStr.PackageUIPanelTips_1 = "丢弃成功"
LabelChineseStr.DayTaskUIPanel_1 = "需要花费"
LabelChineseStr.NpcFunctionTip_1 = "级开放日常任务"
LabelChineseStr.NpcFunctionTip_2 = "级开放锻造"
LabelChineseStr.NpcFunctionTip_3 = "级开放回收"
LabelChineseStr.NpcFunctionTip_4 = "级开放宝石系统"
LabelChineseStr.NpcFunctionTip_5 = "级开放附魔"
LabelChineseStr.NpcFunctionUIPanel_1 = "杂货店"
LabelChineseStr.NpcFunctionUIPanel_2 = "神秘商店"
LabelChineseStr.NpcFunctionUIPanel_3 = "回收站"
LabelChineseStr.NpcFunctionUIPanel_4 = "兑换商人"
LabelChineseStr.NpcFunctionUIPanel_5 = "锻  造"
LabelChineseStr.NpcFunctionUIPanel_6 = "炼  金"
LabelChineseStr.NpcFunctionUIPanel_7 = "酒  馆"
LabelChineseStr.NpcFunctionUIPanel_8 = "探  索"
LabelChineseStr.NpcFunctionUIPanel_9 = "日常任务"
LabelChineseStr.NpcFunctionUIPanel_10 = "回  收"
LabelChineseStr.NpcFunctionUIPanel_11 = "附  魔"
LabelChineseStr.NpcFunctionUIPanel_12 = "宝石合成"
LabelChineseStr.NpcFunctionUIPanel_13 = "宝石加工"
LabelChineseStr.NpcFunctionUIPanel_14 = "附魔融合"
LabelChineseStr.NpcFunctionUIPanel_15 = "仓  库"
LabelChineseStr.HeroTeamUIPanel_1 = "更换队长成功"
LabelChineseStr.LifeSkillsUIPanel_1 = "级开放生活系统"
LabelChineseStr.LifeSkillsUIPanel_2 = "您还尚未建造"
LabelChineseStr.LifeSkillsUIPanel_3 = "挂机状态不允许重建"
LabelChineseStr.LifeSkillsUIPanel_4 = "需要花费"
LabelChineseStr.LifeSkillsUIPanel_5 = "已结束"
LabelChineseStr.LifeSkillsUIPanel_rule = "生活强奸了大家"
LabelChineseStr.LifeSkillsSetUIPanel_1 = "尚未开始"
LabelChineseStr.LifeSkillsSetUIPanel_2 = "挂机列表不能为空"
LabelChineseStr.LifeSkillsSetUIPanel_3 = "挂机状态无法跟换英雄"
LabelChineseStr.NotescontactUIPanel_1 = "标题或内容为空,请重新输入！"
LabelChineseStr.NotescontactUIPanel_2 = "意见提交成功!"
LabelChineseStr.GroceryUIPanel_1 = "花费金币:"
LabelChineseStr.GroceryUIPanel_2 = "获得金币:"
LabelChineseStr.MainMenuUIPanel_1 = "背包已开放"
LabelChineseStr.MainMenuUIPanel_2 = "团长技能已开放"
LabelChineseStr.MainMenuUIPanel_3 = "好友已开放"
LabelChineseStr.MainMenuUIPanel_4 = "生活已开放"
LabelChineseStr.MainMenuUIPanel_5 = "商城已开放"
LabelChineseStr.MainMenuUIPanel_6 = "公会已开放"
LabelChineseStr.MainMenuUIPanel_7 = "成就系统5级以上才会开放"

LabelChineseStr.LoginServerListUIPanel_1 = "区"
LabelChineseStr.LoginServerListUIPanel_2 = "推荐"
LabelChineseStr.LoginServerListUIPanel_3 = "服务器:"
LabelChineseStr.LoginServerListUIPanel_4 = "新区"
LabelChineseStr.LoginServerListUIPanel_5 = "火爆"
LabelChineseStr.LoginServerListUIPanel_6 = "维护"

LabelChineseStr.WorldMapUIPanel_1 = "确认传送至"
LabelChineseStr.NoticeUIPanel_1 = "春节冲级狂欢夜\n\n亲爱的艾泽大陆的勇士们，我是你们的梦想灵魂导师！\n现在告诉你们一个好消息，凡是在2月18日到2月24日期间，等级达到30级，皆可获得梦想灵魂大礼包！里面除了能得的金币5W，钻石500外还能获得目前艾泽大陆最强的法师英雄—特斯拉·拉杆！！！！"
LabelChineseStr.PKUIPanel_1 = "级开放竞技场"

LabelChineseStr.ForgeUIButtonName_1 = "锻  造"
LabelChineseStr.ForgeUIButtonName_2 = "回  收"
LabelChineseStr.ForgeUIButtonName_3 = "取消锻造"
LabelChineseStr.ForgeUIButtonName_4 = "取消回收"
LabelChineseStr.ForgeUISliderName_1 = "正在锻造"
LabelChineseStr.ForgeUISliderName_2 = "正在回收"
LabelChineseStr.ForgeUITip_1 = "锻造成功"
LabelChineseStr.ForgeUITip_2 = "回收成功"
LabelChineseStr.ForgeLookUITip_1 = "熔炼成功"
LabelChineseStr.ForgeLookUITitle_1 = "请输入数量"
LabelChineseStr.ForgeLookUITitle_2 = "最 大"
LabelChineseStr.ForgeLookUISliderName_1 = "正在熔炼"

LabelChineseStr.EnchantUITip_0 = "附魔成功"
LabelChineseStr.EnchantUITip_1 = "附魔失败"
LabelChineseStr.EnchantUISliderName_0 = "正在附魔"
LabelChineseStr.magicName = "附魔" --卷轴道具的道具id的终点

LabelChineseStr.GemSynthesisUITitle_0 = "宝石合成"
LabelChineseStr.GemSynthesisUIButtonName_0 = "合  成"
LabelChineseStr.GemSynthesisUIButtonName_1 = "取消合成"
LabelChineseStr.GemSynthesisUISliderName_0 = "正在合成"
LabelChineseStr.GemSynthesisLookUITip_1 = "切割成功"
LabelChineseStr.GemSynthesisLookUISliderName_1 = "正在切割"

LabelChineseStr.dodge = "闪避"
LabelChineseStr.parry = "格挡"
LabelChineseStr.crit = "暴击"

LabelChineseStr.ErrorDialogUIPanel_1 = "未知错误！"

LabelChineseStr.LoadingTipsUIPanel_1 = "地图上的矿石可以多次采集"
LabelChineseStr.LoadingTipsUIPanel_2 = "在采集时要小心怪物的袭击"
LabelChineseStr.LoadingTipsUIPanel_3 = "小心某些暴躁的怪物可能会主动攻击你"
LabelChineseStr.LoadingTipsUIPanel_4 = "你可以邀请好友一起作战使战斗变得更加轻松"
LabelChineseStr.LoadingTipsUIPanel_5 = "据说联盟国王和大主教并不是情侣？"
LabelChineseStr.LoadingTipsUIPanel_6 = "感觉上来说暗夜精灵的移动速度会比较快"
LabelChineseStr.LoadingTipsUIPanel_7 = "一个人走在野外的时候要小心你的周围"

LabelChineseStr.NotescontactUIPanelTitles_1 = "账号问题"
LabelChineseStr.NotescontactUIPanelTitles_2 = "充值问题"
LabelChineseStr.NotescontactUIPanelTitles_3 = "BUG提交"
LabelChineseStr.NotescontactUIPanelTitles_4 = "游戏建议"
LabelChineseStr.NotescontactUIPanelTitles_5 = "其他问题"

LabelChineseStr.DialogRewardsNewUIPanel_1 = "你什么也没有钓到..."

LabelChineseStr.ChangeNameUIPanelTips_1 = "改名成功"
LabelChineseStr.ChangeNameUIPanelTips_2 = "当前拥有更名牌："
LabelChineseStr.ChangeNameUIPanelLab_1 = " 或者"
LabelChineseStr.ChangeNameUIPanelLab_2 = " 可以修改名称"
LabelChineseStr.ChangeNameUIPanelError = {"未知", "命名过短", "命名过长", "包含空格", "包含非法字符"}

LabelChineseStr.SignSystemUIPanelLab_1 = "第"
LabelChineseStr.SignSystemUIPanelLab_2 = "天"

LabelChineseStr.RepertoryStoreUIPanelTips_1 = "成功存入"
LabelChineseStr.RepertoryStoreUIPanelTips_2 = "成功取出"
LabelChineseStr.RepertoryStoreUIPanelTips_3 = "成功解锁格子"

LabelChineseStr.SystemRulerUIPanelText_1 = {title = "探索规则", rulers = "* 我的规则是探索就是探索探索就是探索探索就是探索探索就是探索探索就是探索探索就是探索探索就是探索探索就是探索探索就是探索探索就是探索探索就是探索探索就是探索探索就是探索探索就是探索探索就是探索探索就是探索探索就是探索探索就是探索探索就是探索探索就是探索探索就是探索探索就是探索探索就是探索探索就是探索探索就是探索探索就是探索探索就是探索探索就是探索探索就是探索探索就是探索探索就是探索探索就是探索探索就是探索探索就是探索探索就是探索探索就是探索探索就是探索探索就是探索探索就是探索探索就是探索探索就是探索探索就是探索探索就是探索探索就是探索探索就是探索探索就是探索探索就是探索探索就是探索探索就是探索探索就是探索探索就是探索探索就是探索探索就是探索探索就是探索探索就是探索探索就是探索探索就是探索探索就是探索探索就是探索探索就是探索探索就是探索探索就是探索探索就是探索探索就是探索探索就是探索探索就是探索探索就是探索探索就是探索探索就是探索探索就是探索探索就是探索探索就是探索\n* 不探索就不探索\n* 探索还是不探索"}
LabelChineseStr.SystemRulerUIPanelText_2 = {title = "团长技能规则", rulers = "* 团长技能就是不停的放技能放呀放呀放呀\n* 技能可以放可以不放呀不放呀不放呀不放呀不放呀不放\n* 技能可以放可以不放呀不放呀不放呀不放呀不放呀不放"}


LabelChineseStr.FriendLineupUIPanel_Attr = {strength = "力 量", agile = "敏 捷", intelligence = "智 力", stamina = "耐 力"
, hp = "生 命", attackPower = "攻击强度", magicPower = "法术强度"
, phyCrit = "护 甲", armor = "抗 性", resistance = "暴 击"
, dodge = "闪 躲", parry = "格 挡", speedUp = "急 速"}

LabelChineseStr.AssistantUIPanelStatus_0 = "未完成"
LabelChineseStr.AssistantUIPanelStatus_1 = "已完成"
LabelChineseStr.AssistantUIPanelTitle_0 = "达到活跃值"
LabelChineseStr.AssistantUIPanelTitle_1 = "还需"
LabelChineseStr.AssistantUIPanelTitle_2 = "活跃度！"

LabelChineseStr.MarqueeSenderUIPanelTips_1 = "发送内容不能为空！"